package InterviewQuestions;
/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.*/

public class findTheDifference {
    public static void main(String args[]){
        //System.out.println(findTheDifference("abc","ae"));
        System.out.println(findTheDifference1("abc","abce"));
    }
    public static char findTheDifference(String s, String t){
        String both = s + t;
        char ret = 0;
        for(char i : both.toCharArray()){
            ret ^= i;
        }
        return ret;
    }

    public static char findTheDifference1(String s, String t) {
        char[] comb = (s+t).toCharArray();
        int output = 0;
        for(char c:comb){
            output = output^c;
            System.out.println(output);
        }
        return Character.toChars(output)[0];
    }

}
